### ISSUE TITLE
 Black screen and write:

### ISSUE THREAD

**Issue by HighTechnological** [SniperGER/Framework7-WatchUI#1]
"Uncaught ReferenceError: Framework7 is not defined"  ---> Framework7.prototype.plugins.WatchUI = function(app, params) {

My js in proect:

src="Watch/js/lib/jquery.js"></script>
 src="Watch/js/lib/jquery.easing.1.3.js"></script>
src="Watch/js/lib/fastclick.js"></script>
src="Watch/js/lib/velocity.min.js"></script>
src="Watch/js/lib/hammer.min.js"></script>
src="Watch/js/WatchUI-1.0.1.js"></script>

src="dist/js/framework7.js"></script>"

**Comment by SniperGER** [comment]
Have you included Framework7 in your project?

**Comment by SniperGER** [comment]
You need to include Framework7 before you include WatchUI. Otherwise WatchUI can't find a variable called "Framework7".

**Comment by HighTechnological** [comment]
Thank you
