### ISSUE TITLE
Question plugin.

### ISSUE THREAD

**Issue by matudelatower** [SniperGER/Framework7-WatchUI#3]
Great job. 

I would like to know which plugin you used to make the presentation.

![captura de pantalla de 2016-04-21 14 44 55](https://cloud.githubusercontent.com/assets/5694115/14719024/344b64e8-07d0-11e6-848d-e81c3bfd66c6.png)

Thanks in advance

**Comment by SniperGER** [comment]
This isn't a plugin. That's just a small script I wrote to display a few images that explain how the demo works and that's it.

You can see the code in the index.html (in the gh-pages branch) in the script block right before the closing </body> tag
